import Head from "next/head";
import { Container } from "@chakra-ui/react";
import NavigationMenu from "@packages/components/NavigationMenu";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationMenu />

      <Container>
        <main>Main</main>

        <footer>Footer</footer>
      </Container>
    </>
  );
}
